name: AOS
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - netcdf4
  - numpy
  - xarray
  - matplotlib
  - seawater
  - cartopy
  - seaborn
  - gsw
  - pip:
      - git+http://github.com/euroargodev/argopy.git@master
